// Generated by LiveScript 1.6.0
(function(){
  var cheerio, request, search, file, out$ = typeof exports != 'undefined' && exports || this;
  cheerio = require('cheerio');
  request = require("sync-request");
  out$.search = search = function(it){
    var url, data, suggestion, dom;
    url = "https://searx.bndkt.io/search?q=" + it.q + "&category=" + (it.type || "general") + "&pageno=" + (it.page || 1) + "&language=all&time_range=&safesearch=" + (it.safe || 0) + "&theme=simple";
    data = [];
    suggestion = [];
    dom = cheerio.load(request("GET", url).getBody());
    dom(".result").each(function(){
      var dt;
      dt = {
        title: dom(this).find("h3").text(),
        content: dom(this).find(".content").text(),
        url: dom(this).find(".url_wrapper").text().split(" › ")
      };
      return data.push(dt);
    });
    dom(".suggestion").each(function(){
      return suggestion.push(dom(this).val());
    });
    return {
      suggestion: suggestion,
      result: data
    };
  };
  out$.file = file = function(it){
    var url, data, dom;
    url = "https://searx.bndkt.io/search?q=" + it.q + "&categories=files&pageno=" + (it.page || 1) + "&language=all&time_range=&safesearch=" + (it.safe || 0) + "&theme=simple";
    data = [];
    dom = cheerio.load(request("GET", url).getBody());
    dom(".result").each(function(){
      var dt;
      dt = {
        title: dom(this).find("h3").text(),
        magnet: dom(this).find(".magnetlink").attr("href"),
        status: dom(this).find(".stat").text(),
        url: dom(this).find(".url_wrapper").text().split(" › ")
      };
      return data.push(dt);
    });
    return data;
  };
}).call(this);
